# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern:   ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: login_check
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # Include the following line to also secure the /admin path itself
        # - { path: ^/admin$, roles: ROLE_ADMIN }
        - { path: ^/compte, roles: ROLE_USER }
        - { path: ^/catalogue, roles: ROLE_USER }
        - { path: ^/panier, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_USER:       ROLE_USER_EXPIRED
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Bdloc\AppBundle\Entity\User } #, property: username

    encoders:
        Bdloc\AppBundle\Entity\User:
            algorithm:   sha512
            iterations: 5000
            encode_as_base64: false